name: Check Log File Before Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if log file exists
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout -b ${{ github.head_ref }}
          LOG_FILE_PATH="^merge-extra-info/log.md$"
          if git diff --name-only origin/${{ github.base_ref }} | grep -qE $LOG_FILE_PATH
          then
            echo "合并日志文件存在，允许合并 ✅"
          else
            echo "❌ 没有设置日志文件，请在.versions文件夹中补充.log.md文件后重新触发任务！"
            exit 1
          fi
